rules_folder: rules

run_every:
  minutes: 1
buffer_time:
  minutes: 15

es_host: 127.0.0.1
es_port: 9200

es_username: elastic
es_password: elastic

writeback_index: elastalert_status
writeback_alias: elastalert_alerts

alert_time_limit:
  days: 2
